# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models

from bruins_app.models import Player_stats


def bruin():
    with open("player_roster.csv") as roster:
        team_data = []
        for items in roster.readlines():
            team_data.append(items.split(','))
    for player in team_data:
        Player_stats.objects.create(
            player_number=player[0],
            player_name=player[1],
            player_position=player[2],
            player_age=player[3],
            player_height=player[4],
            player_weight=player[5],
            shoots_catches=player[6],
            years_exp=player[7],
            birth_date=player[8],
            summary=player[9]
        )
    #raise Exception("FAILLLLL!!!!")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('player_name', models.CharField(max_length=30)),
                ('player_position', models.CharField(max_length=30)),
                ('player_age', models.IntegerField()),
                ('player_height', models.CharField(max_length=10)),
                ('player_weight', models.IntegerField()),
                ('shoots_catches', models.CharField(max_length=10)),
                ('years_exp', models.IntegerField()),
                ('birth_date', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=20)),
            ],

        ),


    ]
