# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:26
from __future__ import unicode_literals

from django.db import migrations

from bruins_app.models import Player_stats


def bruin(*args):
    with open("player_roster.csv") as roster:
        team_data = []
        for items in roster.readlines():
            team_data.append(items.split(','))
    for player in team_data:
        # print(player)
        if player[7] == 'R':
            player[7] = 0
        Player_stats.objects.create(
            player_number=player[0],
            player_name=player[1],
            player_position=player[2],
            player_age=player[3],
            player_height=player[4],
            player_weight=player[5],
            shoots_catches=player[6],
            years_exp=player[7],
            birth_date=player[8],
            summary=player[9]
        )
    # raise Exception("FAILLLLL!!!!")


class Migration(migrations.Migration):

    dependencies = [
        ('bruins_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bruin)
    ]
